example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path, include
from wishlist.views import show_wishlist_ajax, login_user, show_json, show_json_by_id, show_wishlist, show_xml, register, login_user, logout_user


app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('wishlist-ajax', show_wishlist_ajax, name='wishlist-ajax')
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.
class BarangWishList(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
import datetime

from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.core import serializers
from django.urls import reverse
from django.shortcuts import redirect
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

from wishlist.models import BarangWishList

# Create your views here.
@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishList.objects.all()
    context = {
        'list_barang' : data_barang_wishlist,
        'nama' : 'Jason Irvine M.P',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)

@login_required(login_url='/wishlist/login/')
def show_wishlist_ajax(request):
    data_barang_wishlist = BarangWishList.objects.all()
    context = {
        'list_barang' : data_barang_wishlist,
        'nama' : 'Jason Irvine M.P',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist_ajax.html", context)

def show_xml(request):
    data = BarangWishList.objects.all()
    return HttpResponse(serializers.serialize('xml', data), content_type = "application/xml")

def show_json(request):
    data = BarangWishList.objects.all()
    return HttpResponse(serializers.serialize('json',data), content_type = 'application/json')

def show_json_by_id(request,id):
    data = BarangWishList.objects.filter(pk=id)
    return HttpResponse(serializers.serialize('json',data), content_type = 'application/json')

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
        else:
            messages.success(request, 'Akun tidak dapat dibuat')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class="mx-auto" style="width: 1000px;">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class="mx-auto" style="width: 1000px;">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}

<nav class="navbar navbar-expand-lg navbar-light bg-light"> 
    <a class="navbar-brand" href="#">{{nama}}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
            <a class="navbar-brand" href="{% url 'wishlist:logout' %}"><img src="https://cdn.icon-icons.com/icons2/2248/PNG/512/logout_icon_138409.png" width="30" height="30" class="d-inline-block align-top" alt="">Logout</a>
        </li>
      </ul>
    </div>
</nav>

<div class="mx-auto" style="width: 1000px;">
    <br>
    <table class="table">
        <thead class="thead-dark">
            <tr>
            <th>Nama Barang</th>
            <th>Harga Barang</th>
            <th>Deskripsi</th>
            </tr>
            {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
            {% for barang in list_barang %}
                <tbody>
                    <th>{{barang.nama_barang}}</th>
                    <th>{{barang.harga_barang}}</th>
                    <th>{{barang.deskripsi}}</th>
                </tbody>
            {% endfor %}
        </thead>
    </table>
    <br>
    <br>
    <h5>Sesi terakhir login: {{ last_login }}</h5>
</div>

{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block content %}

<nav class="navbar navbar-expand-lg navbar-light bg-light"> 
    <a class="navbar-brand" href="#">{{nama}}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
            <a class="navbar-brand" href="{% url 'wishlist:logout' %}"><img src="https://cdn.icon-icons.com/icons2/2248/PNG/512/logout_icon_138409.png" width="30" height="30" class="d-inline-block align-top" alt="">Logout</a>
        </li>
      </ul>
    </div>
</nav>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    
    $.ajax({
        type: 'GET',
        url: 'http://127.0.0.1:8000/wishlist/json/',
        dataType: 'json',
        success: function (data) {
            var data1 = JSON.stringify(data);
            var items = JSON.parse(data1)
            
            for (var i = 0; i < data.length; i++) {
                var row = $('<tr><td>' + items[i].fields['nama_barang']+ '</td><td>' + items[i].fields['harga_barang'] + '</td><td>' + items[i].fields['deskripsi'] + '</td></tr>');
                $('#data_barang').append(row);
            }
        },
    });
</script>
<div class="mx-auto" style="width: 1000px;">
    <br>
    <table id = "data_barang" class="table">
        <thead class="thead-dark">
            <tr>
            <th>Nama Barang</th>
            <th>Harga Barang</th>
            <th>Deskripsi</th>
            </tr>
            {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
        </thead>
    </table>
    <br>
    <br>
    <h5>Sesi terakhir login: {{ last_login }}</h5>
</div>

{% endblock content %}